
# make sure we get the same MPI version on all hosts
os_type: centos
os_version: "7.1"
tasks:
- ceph:
    log-whitelist: ['HEALTH_WARN']
- pexec:
    clients:
       - cd $TESTDIR
       - wget http://download.ceph.com/qa/fsx-mpi.c
       - mpicc fsx-mpi.c -o fsx-mpi
       - rm -rf fsx-mpi.c
       - ln -s $TESTDIR/mnt.* $TESTDIR/gmnt
- mpi:
    exec: sudo $TESTDIR/fsx-mpi -o 1MB -N 50000 -p 10000 -l 1048576 $TESTDIR/gmnt/test
    workdir: $TESTDIR/gmnt
- pexec:
    all:
      - rm $TESTDIR/gmnt
      - rm $TESTDIR/fsx-mpi     
